[package]
name = "czoodle-server"
version = "0.2.0"
authors = ["Jaroslav Havlin <jaroslav.havlin@gmail.com>"]
edition = "2021"

[dependencies]
actix-web = "4"
actix-files = "0.6.2"
serde = { version = "1.0.171", features = ["derive"] }
serde_json = "1.0.103"
chrono = "0.4.26"
sha2 = "0.10.7"
